apiVersion: v1
kind: Pod
metadata:
  name: gpu-operator-test-2
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      #image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
      image: "nvidia/cuda:12.3.1-runtime-ubuntu22.04"
      command: ["/bin/sh"]
      args: ["-c", "tail -f /dev/null"]
      resources:
        limits:
          nvidia.com/gpu: 1
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

